name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  jobs:
    type-check:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [ 17.x ]
      steps:
        - name: Checkout Commit
          uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node }}
          uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
        - name: install modules
          run: npm install
        - name: Check types
          run: npm run lint:ts
        unit-test:
          runs-on: ubuntu-latest
          strategy:
            matrix:
              node-version: [ 17.x ]
          steps:
            - name: Checkout Commit
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node }}
            - name: linting css
              run: npm run lint:scss
        build:
          runs-on: ubuntu-latest
          strategy:
            matrix:
              node-version: [ 17.x ]
          needs: [ type-check, unit-test ]
          steps:
            - name: Checkout Commit
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v1
            with:
              node-version: ${{ matrix.node }}
            - name: build production project
              run: npm run build:prod
            - name: unit testing
              run: npm run test:unit
            - name: build storybook
              run: npm run storybook:build
            - name: screenshot testing
              run: npm run test:ui:ci
